baseURL = 'https://sus-domesticus.github.io/'
languageCode = 'en-us'
title = 'Marc Grec'
theme = 'PaperMod'
enableEmoji = true

[params.homeInfoParams]
Title = "Welcome!"
Content = "Below are some of my posts. Check out my [portfolio](/categories/project-showcase/) or read more [here](/about/)."

[[menu.main]]
name = "About me"
url = "/about/"
weight = 5

[[menu.main]]
name = "Portfolio"
url = "/categories/project-showcase/"
weight = 10

[[menu.main]]
name = "Contact"
url = "mailto:marcgrec@tuta.com"
weight = 15

[[menu.main]]
name = "GitHub"
url = "https://github.com/sus-domesticus/sus-domesticus.github.io"
weight = 30
